parameters:
#    open_scrum_user.example.class: OpenScrum\UserBundle\Example

services:
#    open_scrum_user.example:
#        class: %open_scrum_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
